name: 'Hello World'
description: 'Greet someone'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: abhay.sh
      shell: bash
    - run: git config --global user.name 'My name'
      shell: bash
    - run: git config --global user.email 'your-username@users.noreply.github.com'
      shell: bash
    - run: git commit -am "Automated"
      shell: bash
    - run: git push
      shell: bash
